[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"
authors = ["Damien Wilson"]
license = "CC0-1.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
